### ISSUE TITLE
Results for f32-based plane normal computation slightly off using cross() and normalize()

### ISSUE THREAD

**Issue by Nevsden** [dimforge/nalgebra#1124]
There seems to be a slight rounding issue with f32-based matrices and the `normalize()` function.
If you follow the playground and check the normalized vectors at the end, they do not match.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dfaf49cd7723a373e173a38b61d4169f

**Comment by Ralith** [comment]
The results are very, very close, and nalgebra does not guarantee rounding equivalent to a specific implementation, What is the issue?

**Comment by sebcrozet** [comment]
Both your manual normalization and the normalization made by `nalgebra` suffer from rounding errors. The error are slightly different because you are doing `vector * inv_norm` whereas `nalgebra` is doing `vector / norm`.  Both are doing slightly different (but mathematically equivalent) operations that yield slightly different rounding errors.

**Comment by Nevsden** [comment]
@Ralith The problem was, that I wanted the results to be equal and did not understand, that both had a rounding error.
@sebcrozet Thank you for pointing out, the rounding error is in both computations. Of course it is. I have learned a lot.

Issue can be closed.
