### ISSUE TITLE
CI fails in the build-cuda step

### ISSUE THREAD

**Issue by patowen** [dimforge/nalgebra#1155]
The CI process currently fails every PR in the build-cuda step due to the changes in #1112. I believe there are multiple ways to fix this:

- Use the latest nightly version instead of a specific version when building for CUDA
- Update the Rust nightly version (much like what was done in 229c137756fc4f71c4cef45ac7c851e7989703b9)
- Use the latest Rust stable version instead of nightly (I haven't researched if this is possible, and I expect it's not)
- Revert #1112 (not the ideal solution)
- Add a non-const version specifically for targeting CUDA, probably using the `cfg` attribute (as suggested in https://github.com/dimforge/nalgebra/pull/1141#issuecomment-1220832380)

I believe the code to modify is at https://github.com/dimforge/nalgebra/blob/7adecdef6c8abbb92cbab0d99825d4a89a73b1a4/.github/workflows/nalgebra-ci-build.yml#L129-L133
I would create a PR, but I don't have enough context to know which bullet point is preferred.

**Comment by sebcrozet** [comment]
Hi! I’ll take care of this in #1156. We can’t use stable or update the nigthly version because rust-cuda requires a [specific version of the compiler](https://github.com/Rust-GPU/Rust-CUDA/blob/master/rust-toolchain). The clean fix would be to revert `Point::new` being const, but it feels unfortunate to remove this for everybody where it’s only really an issue when using `cuda`.

So let’s just add a non-const version behind a `cfg` feature flag. This does go against the additive nature of cargo features, but I think it’s fine for now.

**Comment by patowen** [comment]
Oh, got it. This limitation is clearly written at https://github.com/Rust-GPU/Rust-CUDA/blob/master/guide/src/guide/getting_started.md#rust-toolchain. Thanks for the fix!
