### ISSUE TITLE
how to sub a vector row by row with nalgebra?

### ISSUE THREAD

**Issue by guchengxi1994** [dimforge/nalgebra#1195]
I can do this with numpy like this
```python
import numpy as np

x = np.random.randint(0, 10, (4, 3))

print(x)

v = np.array([1, 2, 3])

b = x - v

print(b)
```

But i cannot find out how to do the same thing with nalgebra? Could someone help me?

**Comment by sebcrozet** [comment]
Hi! You could do something like this:

```rust
    let mut mat = Matrix4x3::repeat(1);
    let vec = RowVector3::new(1, 2, 3);
    mat.row_iter_mut().for_each(|mut row| row -= vec);
```

**Comment by guchengxi1994** [comment]
@sebcrozet Thanks for your advice, but according to your advide, I was using `RowVector` to construct a vector, but it seems not right
```rust
let m = rs.row_mean();
let _v = m.as_slice().to_vec();
for row in rs.row_iter_mut(){
      row = row - RowVector::from_vec(_v);       
}
```
`rs` is a Matrix.
![image](https://user-images.githubusercontent.com/33513462/213835434-e037fb72-b8de-46fe-85ed-79c6cb38f4fc.png)
I cannot fix this ...

**Comment by sebcrozet** [comment]
The error here originates from the fact that the compiler doesn’t know what kind of row vector you want (dynamically sized? staticaly sized?) So you can for example do `DRowVector::from_vec(_v)` instead, where `DRowVector` is a dynamically sized row vector.

Anyway, you don’t need that conversion at all. Your variable `m` is already a row vector (because `row_mean` returns a row vector). So the `to_vec/from_vec` are not needed.

In addition, you can’t do `row = row - RowVector::from_vec(_v)` because `row` is a matrix view (whereas the result of a binary operation must be a whole new vector, it can’t be a view on an existing vector). So you need to apply the subtraction in-place:

```rust
let mean = rs.row_mean();
for mut row in rs.row_iter_mut() {
    row -= &mean;
}
```

**Comment by guchengxi1994** [comment]
@sebcrozet Thanks for your help!

**Comment by wesley800** [comment]
@sebcrozet Sorry but I didn't found the `DRowVector` type. Maybe we just left out `pub type DRowVector<T>=Matrix<T, U1, Dyn, VecStorage<T, U1, Dyn>>;` somewhere?

BTW I have another question but not sure if it's worth a new issue. I'm trying to subtracting a row from another row within the same matrix. Of course this can't be written like in other languages because of rust's borrow checker. So I have to copy the subtractee into a new `DRowVector` (and that's in fact why I found this issue) like this:

```rust
pub type DRowVector<T>=Matrix<T, U1, Dyn, VecStorage<T, U1, Dyn>>;
let t: DRowVector<f64> = mat.row(i-1).into();
mat.row_mut(i).sub_assign(t);
```

which seems to be redundant. Are there already a zero-copy way for this operation, or shall we add something like `split_at_mut`?
