### ISSUE TITLE
Incorrect statement about assignment for matrix views in user guide

### ISSUE THREAD

**Issue by Andlon** [dimforge/nalgebra#1224]
This came up during [discussion in the forum](https://github.com/dimforge/nalgebra/discussions/1223#discussion-5042170).

According to the user guide:

> Assignment operators do not work on any kind of view, i.e., one cannot write a *= b even if a is a mutable matrix view.

This is incorrect, since for example the following example works:

```rust
use nalgebra::{matrix, vector};

fn main() {
    let mut a = matrix![1.0, 2.0; 3.0, 4.0];
    let mut b = a.fixed_view_mut::<2, 1>(0, 0);
    let c = vector![5.0, 6.0];
    b += c;
}
```

This should be corrected to say that the assignment operator `=` does not work for views (and this is an inherent limitation of Rust, not of `nalgebra`).

**Comment by robbespo00** [comment]
I do not understand correctly. what is the meaning. 

Do you mean that the assignment operator `=` does not work for views due to the fact that if you try:
```rust
use nalgebra::{matrix, vector};

fn main() {
    let mut a = matrix![1.0, 2.0; 3.0, 4.0];
    let mut b = a.fixed_view_mut::<2, 1>(0, 0);
    let c = vector![5.0, 6.0];
    b = c;
}
```
It fails because it is a vector? 
But in general you are allowed to assign `=` a view to another view (if they have the same dimensions) like here:
```rust
use nalgebra::{matrix, vector};

fn main() {
    let mut a = matrix![1.0, 2.0; 3.0, 4.0];
    let mut b = a.fixed_view_mut::<2, 1>(0, 0);

    let mut d = matrix![5.0, 6.0; 7.0, 8.0];
    let mut c = d.fixed_view_mut::<2, 1>(0, 0);
    b = c;
}
```

**Comment by Andlon** [comment]
I'm... actually not sure what makes sense to say here. We also cannot use `=` to assign to a matrix, we also have to use `.copy_from` there, so there doesn't seem to be any particular limitations of views here. I'm not sure, @sebcrozet maybe you can elaborate on what you had in mind in the discussion forum post?

**Comment by sebcrozet** [comment]
With non-view matrices we can do this:
```rust
let mut a = matrix![1, 2; 3, 4];
let b = matrix![10, 11; 12, 13];
a = b;
assert_eq!(a, b);
```

With view matrices, we can’t do this:
```rust
let mut a = matrix![1, 2; 3, 4];
let b = matrix![10, 11; 12, 13];
let mut view_a = a.fixed_view_mut::<2, 2>();
view_a = b;
```
Which makes sense, since `view_a` and `b` don’t have the same type anyway.

But I’ve seen many beginners struggle with the fact that it doesn’t compile. They usually expect that this effectively fills `view_a` with the content of `b`.

Or even worst, they will often assume that doing `view_a = view_b` will actually change the content of the matrix targeted by `view_a` (just like `a = b` changes the value identified by `a`).

All this is obvious when you are very familiar with rust and have some experience with `nalgebra`. But many users of `nalgebra` come from straight from C++ or python before having a chance to folly grasp the subtlety (or rather, the lack of subtlety) of the semantic of rust’s `=` 

So the message I would like to give in the doc is that `view_a = b` doesn’t compile, and even `view_a = view_b` won’t do what you might think it will when it compiles (i.e. it won’t replace the content of the matrix targeted by `view_a`).

**Comment by robbespo00** [comment]
@Andlon  and @sebcrozet thanks for your support. 
I have opened a pull request on the repository of the documentation. I hope it solved the problem.
