### ISSUE TITLE
Segfault when using `new_random()` on larger matrices

### ISSUE THREAD

**Issue by paulstey** [dimforge/nalgebra#1252]
First, thanks for your phenomenal work on this project!

I ran into what seems to be a weird bug today. I'm getting a segmentation fault when I use the `new_random()` method to allocate larger matrices. The code below segfaults on my M2 Max as well as on a Intel Xeon 8268. 

I would be very grateful for any help you can provide. Thank you so much!

```rust
use nalgebra::base::SMatrix;

fn main() {
    type Matrix = SMatrix<f64, 512, 512>;

    let mat1 = Matrix::new_random();

    println!("{:}", mat1);
}
```

**Comment by paulstey** [comment]
Oh, and here is my `Cargo.toml` file.

```rust
[package]
name = "nalgebra_mat_mul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.2", features = ["rand"] }
```

**Comment by Andlon** [comment]
Judging from your example, this is probably a stack overflow. Can you give the output with debug symbols turned on? It would be great to confirm. If that's the case, you'd probably get the same problem if you don't use `get_random` but instead just `Matrix::repeat(2.0)` (avoiding `0.0` since compilers/allocators etc. sometimes go alternate routes for zeroed memory).

A 512x512  `f64` matrix requires 16 MB stack space, which is likely larger than the stack size your OS uses by default.

For such large matrices, there are usually no benefits to storing them on the stack. I'd recommend to use `DMatrix` instead, if you can.

**Comment by paulstey** [comment]
Thanks so much for your help, @Andlon! 

Your intuition is correct, this seems to be a stack overflow. The output below is what I get with `RUST_BACKTRACE=1`. And yes, you're also correct that I get the same result when using `repeat()` rather than `new_random()`. 

I will use `Dmatrix` as you suggest. Thanks again for your help, @Andlon! And thanks also for this phenomenal crate!!
