### ISSUE TITLE
Dense Sparse Multiplies and Docs Question

### ISSUE THREAD

**Issue by shur-complement** [dimforge/nalgebra#1261]
Hi! Thanks for this very easy to use package.

Recently when implementing some algorithms using `nalgebra`, I had a need for `sparse-dense` and `dense-sparse` multiplies. I see that:
  - [`Csc.mul(Matrix)`](https://docs.rs/nalgebra-sparse/latest/nalgebra_sparse/csc/struct.CscMatrix.html#method.mul)
  - [`Csr.mul(Matrix)`](https://docs.rs/nalgebra-sparse/latest/nalgebra_sparse/csr/struct.CsrMatrix.html#method.mul)
  both exist. Would there be interest in implementations for:
  - `Matrix.mul(Csr)`
  - `Matrix.mul(Csc)`
  
  aka dense-sparse products?
  
  Separately, is there a possibility we could add some `nalgebra-sparse` docs to the main site? I could send a PR for this if interested as well.

**Comment by Andlon** [comment]
Hi @schur-complement! I initially implemented only `sparse-dense` in order to reduce scope, as in my experience `dense-sparse` is pretty rare. But we've had some people requested `dense-sparse` in the meantime. So I think it makes sense to implement this as well.

By "main site", do you mean the user guide? It would indeed be great to have some docs there too, yes. By all means, if you're up to it I'd be happy to have that :-)

Do note, however, that I've been extraordinarily busy for a long time now and I don't expect to have time for reviewing anything substantial for at least the next 1-2 months.

**Comment by shur-complement** [comment]
^ no rush, threw some basic docs together. Took a look at implementing dense-sparse, gonna chip away at that when I have time.
