### ISSUE TITLE
Allow bitshifting matricies if they are integers

### ISSUE THREAD

**Issue by Astralchroma** [dimforge/nalgebra#1341]
See title

**Comment by tpdickso** [comment]
This can be done with a constant bit shift amount using the [map](https://docs.rs/nalgebra/latest/nalgebra/base/struct.Matrix.html#method.map) function on the matrix, or componentwise using the [zip_map](https://docs.rs/nalgebra/latest/nalgebra/base/struct.Matrix.html#method.zip_map) function. Would these work for your use case, or is there a strong reason to have dedicated functions for these?

**Comment by Astralchroma** [comment]
Not really a "strong reason" other than its a basic math operation that could be supported, and all the others are, so why not? Just seemed it had been overlooked, because I couldn't find anything demonstrating a deliberate decision not to implement it.

**Comment by tpdickso** [comment]
In terms of arithmetic operations on matrices, these don't necessarily correspond to simple componentwise operations; the `*` operator implements [matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication), as opposed to just multiplying each entry. `+` and `-` do perform componentwise operations, but this is somewhat "coincidental" due to the fact that adding and subtracting matrices as mathematical objects "works out" to be a componentwise operation (and multiplication doesn't.) So I think the decision not to implement bit-shifts through *operator overloading* specifically is because these operations don't have a well-accepted meaning when applied to matrices, so it might be misleading to users.
