### ISSUE TITLE
SymmetricEigen produces wrong sign of eigenvector values on Matrix6

### ISSUE THREAD

**Issue by yesint** [dimforge/nalgebra#1343]
I'm porting C++ code using Eigen to Rust with nalgebra and came across an error in SymmetricEigen. The eigenvectors produced by nalgebra are different from what is produced by Eigen. The absolute values are the same but the signs of individual eigenvector component differ.

Here is the [example code](https://gist.github.com/rust-play/282d9ed324b5a6fce4a2b8988b349e47).

Here is the result produced by C++ with Eigen. These are _correct_ numbers (taken from tested production code).

```
0.0374127   0.481146  -0.516816  -0.516816  -0.481146  0.0374129
 -0.230172  -0.480963   -0.46443   -0.46443   0.480963  -0.230172
 -0.667549   0.192803   0.131172   0.131172  -0.192803  -0.667548
-0.0374127  -0.481146   0.516816  -0.516816  -0.481146   0.037413
  0.634785    0.20376   0.235649  -0.235649    0.20376  -0.634785
  0.309271  -0.476425  -0.421154   0.421154  -0.476425  -0.309271
```

The result produced by nalgebra. Asteriscs show the wrong signs - the whole eigenvector 4 has wrong signs:
```
  │   0.48114583 -0.037413225    0.5168162   0.51681626   0.48114586*  0.037413023 │
  │  -0.48096305   0.23017226   0.46442991   0.46442974  -0.48096335*  -0.23017228 │
  │    0.1928035    0.6675487  -0.13117145  -0.13117121   0.19280326*   -0.6675486 │
  │  -0.48114595  0.037413254  -0.51681584    0.5168161   0.48114598*  0.037413135 │
  │   0.20375918  -0.63478476  -0.23564915   0.23564912  -0.20375934*   -0.6347847 │
  │  -0.47642478  -0.30927122   0.42115387  -0.42115414   0.47642496*  -0.30927137 │
```

Unless I'm missing something, this is a bug. I just can't port the working code from Eigen to nalgebra, because the algorithm fails due to wrong sign of the eigenvector.

**Comment by Andlon** [comment]
Normalized eigenvectors are not generally unique. As you've observed, you can arbitrarily change their signs while still retaining a valid eigendecomposition for the matrix. For example, we can check that we still get the original matrix back if we recompose the matrix from its eigendecomposition, [as I've done here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ddf45299e455684f39972f6d87227c40) (note that due to limited precision of `f32`, the zero blocks don't "look" very close to zero to a human eye).

As far as I can tell, `nalgebra` appears to be doing the right thing, and the discrepancy between Eigen and `nalgebra` is just due to implementation details. I don't quite understand how you can have an algorithm that fails because the sign is "wrong" - perhaps you can elaborate on this if you think there might still be more to the story.

I'll close this issue for now but feel free to re-open or follow up if you think there is more to address here. Hope this helps!

**Comment by yesint** [comment]
@Andlon thanks a lot for a quick response! Yes, indeed there is an algorithm, which *is* sensitive to this - the alignment of two molecular structures in terms of minimal RMSD.

In this algorithm one computes the eigenvectors of the 6x6 matrix and takes two eigenvectors with the largest eigenvalues (vectors 4 and 5 since they are sorted ascending). After that parts of these vectors are used to construct the transformation matrix that aligns one point cloud to the other. 

The algorithm is [here](https://github.com/yesint/molar/blob/master/src/core/algorithms.rs), look for `rot_transform_matrix`.

I'm not an expert in this algorithm, I've copy-pasted it initially from old C-code and adapted for Eigen in C++. Now I translated it literally to nalgebra and have found an issue with the sign on 4-th eigenvector.

Currently I've just put "-" to invert the offending vector, but this looks like an unreliable hack because I can't guarantee that it will work for all matrices consistently (somehow, for Eigen and older C code it always just works).

I really don't like this kind of "black magic", so I'd be very grateful for any suggestions how to adapt the things to nalgebra way of computing eigenvectors.

**Comment by yesint** [comment]
I don't see a way to re-open an issue, btw.

**Comment by yesint** [comment]
And there is yet another bag candidate :) 
If I compute the eigenvalues of this matrix with `nalgebra::SymmetricEigen` I get this:

```
val =
 
  ┌            ┐
  │ -39261.336 │
  │ -58575.883 │
  │  -17988.87 │
  │  17988.875 │
  │   39261.33 │
  │  58575.883 │
  └            ┘
```
Two first values are not in correct ascending order.

If I do this with with `nalgebra_lapack::SymmetricEigen` I get this:
```
val =
 
  ┌            ┐
  │   -58575.8 │
  │ -39261.313 │
  │ -17988.877 │
  │  17988.863 │
  │  39261.305 │
  │   58575.83 │
  └            ┘
```
Now everything is sorted correctly.
This is weird to say the least.

**Comment by schneiderfelipe** [comment]
> [@Andlon](https://github.com/Andlon) thanks a lot for a quick response! Yes, indeed there is an algorithm, which _is_ sensitive to this - the alignment of two molecular structures in terms of minimal RMSD.
> 
> (...)
> 
> I really don't like this kind of "black magic", so I'd be very grateful for any suggestions how to adapt the things to nalgebra way of computing eigenvectors.

Normally one would check for reflections in the final transform, otherwise you would get a [*general* orthogonal matrix](https://en.wikipedia.org/wiki/Orthogonal_matrix#Matrix_properties) only, not a [*proper* one (i.e., a rotation matrix)](https://en.wikipedia.org/wiki/Rotation_matrix#Properties). This is normally done by checking a determinant. On doing so the algorithm ends up taking those signs into account, no black magic (see the [relevant section on the Wikipedia page for the Kabsch algorithm](https://en.wikipedia.org/wiki/Kabsch_algorithm#Computation_of_the_optimal_rotation_matrix)). When reflections are allowed, people call it the [orthogonal Procrustes problem](https://en.wikipedia.org/wiki/Orthogonal_Procrustes_problem#Generalized/constrained_Procrustes_problems). Hope this helps!

@sebcrozet @Andlon I don't see any problem in giving eigenvectors/eigenvalues in arbitrary order or eigenvectors with arbitrary signs, it's all OK. But it would be nice if it were better documented?
