### ISSUE TITLE
The implementations of base::Matrix::fill_upper_triangle and base::Matrix::fill_lower_triangle functions were reversed

### ISSUE THREAD

**Issue by seanxnie** [dimforge/nalgebra#1451]
Hi, there,
I found that implementations of `base::Matrix::fill_upper_triangle` and `base::Matrix::fill_lower_triangle` functions were reversed. The output of the following code can prove it.
```
use nalgebra::{DMatrix}; // 0.33.0
fn main() {
    let nc: usize = 4;
    let mut a_mat = DMatrix::from_element(nc, nc, 0.0);
    a_mat.fill_upper_triangle(1.0, 0);
    let mut a_t_mat = DMatrix::from_element(nc, nc, 0.0);
    a_t_mat.fill_lower_triangle(1.0, 0);
    println!("a: {:?}, a_t: {:?}", a_mat, a_t_mat);
}
```
Please swap the function name in the implementing code. Thanks.

**Comment by sebcrozet** [comment]
Hi! The result of these functions are correct. If you print with `{}` instead of `{:?}` you will see it more easily:
![image](https://github.com/user-attachments/assets/fb1aa9d3-b2a2-4f70-9648-f0415be8cf98)

Note that matrices are stored in column-major format, which, when viewed as a flat array with `{:?}` might look transpose if you are used to row-major.
