### ISSUE TITLE
Implement a UDU factorization for square matrices

### ISSUE THREAD

**Issue by ChristopherRabotin** [dimforge/nalgebra#762]
A UDU factorization is more stable than an LU decomposition when tackling covariance matrices, as is done in in [nyx-space](https://crates.io/crates/nyx-space), a high-fidelity astrodynamics toolkit. It is in fact [recommended](https://ntrs.nasa.gov/citations/20180003657) for spacecraft navigation by NASA.

## Implementation
I would be thrilled to implement this! @sebcrozet would the best way for me to implement this to start with the [LU decomposition code architecture](https://www.nalgebra.org/rustdoc/src/nalgebra/linalg/lu.rs.html#31-37) and would that source fit in the linalg module?

## Algorithm 
![udu](https://user-images.githubusercontent.com/4823784/92643120-7c286c80-f29e-11ea-9532-824995212a95.png)

**Comment by sebcrozet** [comment]
That would be a great addition, yes!

**Comment by lebensterben** [comment]
Could you explain why SVD/UDU decomposition is more stable than LU decomposition?

From what I read in this paper, it's comparing matrix composition approach, that is SVD/UDU decomposition, to Kalman Filter, rather than comparing SVD to LU.

Also, I have a few suggestions,
- Since covariance matrices are Hermitian matrices, Cholesky decomposition is more efficient than LU decomposition. We should also consider add this.
- The current implementation of LU decomposition is based on Gaussian elimination. Another common algorithm is Crout's method. There is a [paper](https://www.degruyter.com/view/journals/comp/8/1/article-p210.xml?language=en) benchmarked these two methods, and found Gaussian elimination is more efficient for more sparse matrix. So I suggest also to add Crout's method.
- I suggest to use Crout's method when inverting a non-sparse matrix.
- For sparse matrix, use Gaussian elimination for matrix inverse.
- Cholesky decomposition though is more efficient, it only works on Hermitian matrices, so it should not be the default method. But users should be able to manually invokes it.

**Comment by ChristopherRabotin** [comment]
I can't explain why UDU is more stable than LU decomposition because I don't know the algorithms and the proofs well enough. For the validation of the software I'm writing, I need to adhere to the NASA methods for spacecraft navigation, and that's why I volunteer to implement the UDU decomposition in nalgebra.

An implementation of UDU does not preclude implementing Crout's method as you say.

Maybe the `UD` structure (based on the `LU` structure I referenced above) could have two constructors: `new` and `new_crout`?

**Comment by Andlon** [comment]
First, I think having this decomposition would indeed be very valuable. However, I was a very confused about the name `UDU` at first: I think it's almost universally called "LDLT" in other software (see e.g. `Eigen`) and in the literature (to my knowledge). I can only find references to UDU with connection to Kalman filters, signal processing etc, but it seems almost all other applications use the `LDLT` convention.

Of course, this isn't quite the same: `UDU^T` uses upper triangular matrices, and `LDL^T` uses lower triangular matrices. However, `LDLT` is consistent with Cholesky (`LL^T`) and is in fact exactly equivalent (in exact arithmetic) to Cholesky for positive definite matrices. So it seems to me that it would be worthwhile to consider the `LDLT` variant instead of the `UDUT` variant. On the other hand, I can't immediately see a way to easily convert between the `UDU^T` and `LDL^T` representations. The only connection I can find is the following:

For simplicity, let's consider `LLT` and `UUT` instead of `LDLT` and `UDUT` (the argument can be extended to cover this case). Let `L = QR` be the QR decomposition of the Cholesky factor `L`. In other words, `Q` is an orthogonal matrix and `R` upper triangular. Thus we have that `R = LQ^T` and since `Q` is orthogonal (`Q^T Q = I`) we can write

```
A = L L^T = L Q^T Q L^T = R R^T = U U^T
```

so `U = L Q^T` for some orthogonal matrix `Q` obtained by the QR decomposition. Unfortunately, a general-purpose QR decomposition would be too expensive for convenient conversion. However, `L` has very particular structure: it is lower triangular. I would not be surprised to find that there is a fast algorithm to compute the QR decomposition of a lower triangular matrix - unfortunately I don't have more time to derive/find one at the moment... But perhaps we can discuss this further. Note that we wouldn't need the full `QR` decomposition, we would only need to compute the upper triangular factor `R`.

The reason I bring all of this up is that I believe the `LDL^T` decomposition is *far more common* than `UDU^T` so I believe it would have more general utility. On the other hand, if you need an `UDU^T` decomposition, then it's understandable that this is what you want to implement. I was hoping to find a way to (cheaply) convert between the two so that we could have the best of both worlds.

As for numerical stability of `LU` vs `LDL^T` (I assume stability properties of `LDL^T` and `UDU^T` are more or less identical due to the orthogonal transformation that connects them), here are my thoughts:

- It's feasible that by explicitly considering symmetry, `LDL^T` can avoid some loss of precision by avoiding operations that would cause drift away from symmetry. However, I would expect a full-pivot `LU` algorithm to be equally accurate for almost any problem. With partial-pivoting I suppose you can find some corner cases though.
- It's perhaps more worthwhile to discuss `LDLT` vs `LLT` (Cholesky). Cholesky requires computing square roots to form the `L` factors. Even though a matrix is positive definite in exact arithmetic, in some ill-conditioned cases it may be slightly indefinite due to lack of numerical precision. For example, a value `eps` that should be slightly positive might become slighty negative due to lack of precision. Here computing the square root `sqrt(eps)` will completely break the algorithm, whereas `LDL^T` would just absorb the negative value in the `D` factor and the algorithm as a whole might still work.
- `LDL^T` naturally works for certain classes of indefinite matrices. In particular, any *quasi-definite* matrix will have an `LDLT` decomposition, but in general it does not have a Cholesky decomposition.
- Computing square roots is more expensive than simple arithmetic (although it doesn't make a very large difference on modern computers), and might be a source of greater numerical error (depending on the implementation).

Would be interesting to hear your thoughts, @ChristopherRabotin.

**Comment by Andlon** [comment]
I realized I was too quick in my derivation for the connection between LDLT and UDUT - what I did was wrong. I updated my comment accordingly.

**Comment by ChristopherRabotin** [comment]
I agree with you that LDL^T is much more common than UDU^T. In fact, LDL^T is mentioned many, many times in Golub's "Matrix Computations", but UDU^T is only mentioned once for Corollary 11.3.2, in the "Large sparse linear systems problems" chapter.

In my case, it is true that a UDU decomposition is recommended for the kinds of problems I need to solve (Kalman filters for navigation).

However, I'm also happy to implement an LDL^T decomposition using this algorithm by Golub (or another one if you have recommendations). I think for clarity, it would be worth separating those into two different PRs.

![Screenshot_20200918_023212](https://user-images.githubusercontent.com/4823784/93575804-5282db80-f957-11ea-9e8f-86a9284cbd1e.png)

**Comment by Andlon** [comment]
I think it would be nice to have both, and it's great that you're interesting in implementing both! Btw, for the `LDLT` I think it should be almost exactly the same as the Cholesky implementation, so I guess building off of the existing Cholesky impl would make sense.

My only worry is the maintenance burden of having to maintain two very similar but ultimately different algorithms... Although maybe this is not too bad in the end.

**Comment by lebensterben** [comment]
No one calls it UDU. It's more commonly known as Singular Value Decomposition or SVD. An alternative name is Spectral Decomposition.

**Comment by Andlon** [comment]
> No one calls it UDU. It's more commonly known as Singular Value Decomposition or SVD. An alternative name is Spectral Decomposition.

To hopefully avoid some confusion here, note that the `UDU` factorization that @ChristopherRabotin presented defines `U` as upper triangular. Therefore it is not an SVD/spectral decomposition, since in that case `U` would have to be orthogonal.

**Comment by ChristopherRabotin** [comment]
What is the command to run the tests? I've resorted to [pushing to trigger the build](https://github.com/ChristopherRabotin/nalgebra/runs/1164185917), but could iterate faster if I ran the tests locally.

I have this errors when trying to run tests locally (I branched off of `dev`):

```
$ CARGO_FEATURES="alloc" cargo test udu_simple
(...)
   Compiling matrixcompare v0.1.3
   Compiling paste v0.1.18
error[E0432]: unresolved import `num_traits::Float`
 --> /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixcompare-0.1.3/src/comparators.rs:5:18
  |
5 | use num_traits::{Float, Num};
  |                  ^^^^^
  |                  |
  |                  no `Float` in the root
  |                  help: a similar name exists in the module (notice the capitalization): `float`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `matrixcompare`.

```

**Comment by ChristopherRabotin** [comment]
I've started an implementation [here](https://github.com/ChristopherRabotin/nalgebra/tree/762-udu-factorization) but I'm having troubles running the tests. I've branched off from `dev`, and the tests don't build unless on nightly: https://github.com/ChristopherRabotin/nalgebra/runs/1164254051 .

Moreover, I am very concerned that when I try to break the `udu_simple` test, the nightly test is still successful.

How can I run the tests locally?

I can build with `LAPACK=1 CARGO_FEATURE_SYSTEM_NETLIB=1 CARGO_FEATURE_EXCLUDE_LAPACKE=1 CARGO_FEATURE_EXCLUDE_CBLAS=1 sh ci/build.sh` but those flags do not work if I try to execute the script `test.sh`.

Thanks for any help
