### ISSUE TITLE
Should numerical stability be evaluted when inverting a matrix?

### ISSUE THREAD

**Issue by ChristopherRabotin** [dimforge/nalgebra#765]
If I read the [`try_inverse_mut`](https://www.nalgebra.org/rustdoc/src/nalgebra/linalg/inverse.rs.html#29) function correctly (and I might have missed something), the numerical stability of the matrix is not assessed.

Would it make sense to compute the ratio of the largest to smallest eigenvalue of the matrix, and check that this order of magnitude is not larger than what can be represented with the numerical type of the matrix? If so, should that change by done directly in `try_inverse_mut`?

**Comment by Andlon** [comment]
This is a noble goal, but as far as I know, there is no reliable way to assess this. For example, consider the following diagonal matrix `D`:

```
[ 1e9    0       ]
[     0    1e-9 ]
```

This matrix has eigenvalue ratio of ~1e18, which is beyond what can be represented by double-point floating precision. However, its inverse can be exactly computed without issue. This is just one example: I believe to for any such eigenvalue-based metric that you can come up with, you can also come up with a counter-example in which it's entirely reasonable to compute the inverse.

Let me take a less academic and more practical example. I recently worked on a paper in which case indeed the matrix could be almost arbitrarily badly conditioned. However, it did not matter, because the right-hand side `b` in the system `Ax = b` was also correspondingly "small" where the tiny eigenvalues occurred, so that, even though the solution `x` was technically very inaccurate for some components, those components also had effectively zero contribution on the overall solution quality.

At this point we haven't even started discussing complications related to eigenvalue computation:

- Computing eigenvalues is usually more expensive than computing the inverse in the first place.
- Computing small eigenvalues accurately is very difficult, therefore the metric itself might be too inaccurate to be reliable, even if you had a mathematically reliable metric.

I think that, ultimately, only the user can know what is acceptable in terms of numerical error, and furthermore how to deal with it. It is in some sense yet another part of the reality of working with limited numerical precision.

**Comment by Andlon** [comment]
Oh, but that said, I think the docs should be much clearer about what it means for the inversion to "fail", so this should probably be improved!

**Comment by lebensterben** [comment]
>Oh, but that said, I think the docs should be much clearer about what it means for the inversion to "fail", so this should probably be improved!

@Andlon The source code is clear enough. When it's singular, returns false.

**Comment by Andlon** [comment]
> > Oh, but that said, I think the docs should be much clearer about what it means for the inversion to "fail", so this should probably be improved!
> 
> @Andlon The source code is clear enough. When it's singular, returns false.

First, I disagree: For non-small matrices it defers to `lu::try_invert_to`, so you have to do some chasing to get to the bottom of it. 

Additionally, what the source code does is arguably an orthogonal concern. Source code can change, and its current behavior is not guaranteed to stay the same. Documentation, on the other hand, is a contract with the user, and describes the intention of the code. I'd argue that it's never a good idea to rely on current, undocumented behavior when building software.

**Comment by ChristopherRabotin** [comment]
Checkmate ;-) You've made a very good argument and the counterexample you provide is beautiful in its simplicity and effectiveness.

I agree that the documentation could be more clear, but if so, it may be worth another issue.

P.S.: I will be working on #762 next week, so maybe can I add a few words to the `try_inverse_mut` documentation then.

**Comment by lebensterben** [comment]
>If I read the [`try_inverse_mut`](https://www.nalgebra.org/rustdoc/src/nalgebra/linalg/inverse.rs.html#29) function correctly (and I might have missed something), the numerical stability of the matrix is not assessed. ...

@ChristopherRabotin The current implementation of LU decomposition has row permutation, so this is numerically stable in practice.

ref: Trefethen, Lloyd N.; Bau, David (1997), Numerical linear algebra
