### ISSUE TITLE
Segmentation fault when doing dot product of DMatrix

### ISSUE THREAD

**Issue by TimothyBergstrom** [dimforge/nalgebra#776]
Hello,

I was comparing the performance between ndarray and nalgebra and ran into a problem.

gist code: https://gist.github.com/0045efd5c1d490ddb557ebbfc54b4993
rust playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0045efd5c1d490ddb557ebbfc54b4993

The same happens when running locally with cargo build.

Am I doing something wrong, or is there a bug when running the dot product in this particular way?

**Comment by sebcrozet** [comment]
Hi! This is a bug.

nalgebra should panic with a dimension mismatch error instead of segfaulting.
Also keep in mind that `dot` does not have the same meaning in nalgebra and ndarrays. In ndarrays, `dot` between two `Array2` represents matrix multiplication, while in nalgebra it always represents the scalar product (aka. the vector dot product).

So you should compare `x.dot(&y);` from ndarrays, to `&x * &y` from nalgebra.
