### ISSUE TITLE
License compatability issues

### ISSUE THREAD

**Issue by jnqnfe** [dimforge/nalgebra#802]
I would like to bring to your attention the fact that the licensing for some of your crates, such as `nalgebra-glm,` is incompatible with their dependencies.

While Apache-2.0 projects can use MIT licensed components, the reverse is not so. Consider for instance that MIT is GPL v2 compatible, while Apache-2.0 is not; Crates of yours that are MIT licensed that depend upon Apache-2.0 crates are thus misleading to any potential GPL-v2 projects that consider using your crates - they'd end up constructing a non-compliant product.

1. `nalgebra` is Apache-2.0 only licensed; some of your other crates like `nalegbra-glm` depend upon it yet are MIT licensed. To fix this, either `nalgebra` would need to be offered as MIT only or 'MIT OR Apache-2.0', or the crates depending upon it would need switching from MIT to Apache-2.0 only.
2. Some of your crates depend on third-party crates which are Apache-2.0 only, which thus requires such crates of yours to be Apache-2.0 only (you cannot offer MIT).

**Comment by Andlon** [comment]
Hi @jnqnfe, I'm a little confused about what it is you mean here. As far as I know, and according to all available online sources that I could find right now, the MIT and Apache 2.0 licenses *are* compatible with each other, in the sense that you can combine code written in either with the other. Do you have a source saying otherwise?

I also hesitate to agree that it is the responsibility of someone licensing their code under MIT to make sure that it is compatible also for GPL-2 users. This does not sound like a reasonable burden to me - though of course it would be nice if it's the case.

Personally I would *strongly* prefer if everything were MIT, but it may anyway be difficult to change `nalgebra`'s licensing at this point - technically one would need to obtain permission from all contributors, which may not be so easy in practice... (?)

**Comment by sebcrozet** [comment]
I have to admit that I was (and still am) not very well versed when it comes to licensing rules.

> EDIT: I see that nalgebra's license was already switched from BSD-3 to Apache 2.0 ~3 months ago. From a legal perspective, I guess this was not entirely unproblematic...

I am happy to the license files back to BSD-3 if any former contributor think this change was abusive. But because nalgebra has dependencies under the Apache 2.0 license, I am not sure it was possible for us to license it under MIT or BSD-3 in the first place. Following what @jnqnfe said and [that license compatibility graph](https://en.wikipedia.org/wiki/License_compatibility#/media/File:Floss-license-slide-image.svg), the MIT -> Apache 2.0 compatibility is only one-way. But perhaps I am just misunderstanding the meaning of "one-way license compatibility".

**Comment by Andlon** [comment]
I'm not sure if I would trust Wikipedia on this. The linked compatibility graph on Wikipedia comes from the personal webpage of David Wheeler, who, while active in FOSS, as far as I can tell is *not* a lawyer, nor it is his legal opinion. In fact, virtually every other source I can find contradicts the idea that using Apache in MIT-licensed projects is problematic, and the graph on Wikipedia is the *only* source I've seen so far that makes this claim.

For example, according to [this FAQ](https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered):

>3. Is the Apache considered copyleft?
> 
> Copyleft licenses require the derivative works or modified versions of existing software to be released under the same license. The Apache License doesn’t have any such requirements. It’s a permissive license. It permits you to release the modified parts of the code under any license of your choice. However, you are required to release all the unmodified parts of the software under the same license (the Apache License).

You might also simply read the license text. There is no mention at all that any derivative works must have any particular license, as long as the license of the Apache 2.0-licensed work is distributed with the source and appropriate documentation of any modifications is made available. This is in stark contrast to copyleft licenses like the GPL, which expressly state that derivative works *must* be licensed under a GPL-compatible license.

I'm no lawyer, but I still maintain that combining MIT and Apache 2.0 projects is largely unproblematic.

As for the issue of GPL users relying on MIT projects: `nalgebra`'s license only covers `nalgebra`'s code. It is the responsibility of the user to ensure that all the code in the complete distribution (presumably after pulling down all dependencies with `cargo`) is compatible with the GPL. This is, by the way, precisely one of the reasons why MIT is so popular among open source developers: you don't have to be overly concerned with the exact licenses of your dependencies.

**Comment by jnqnfe** [comment]
FWIW, I better state that I'm not a lawyer either, if it's not obvious.

I've spent a lot of additional time further refreshing and improving my understanding of this topic over the past couple of days before responding, it having been a long time since I last read up on it properly and and feeling less confident than I initially had been. It's been proving frustratingly difficult to dig up clear and reliable answers, and repeatedly I've found myself enlightened only to later be hopelessly lost again. I've been wishing for the past several hours now I'd not bothered bringing it up :/.

However, I think I've figured it out now and I believe I made a fundamental mistake in my understanding of how the licensing model works, so I must apologise for wasting your time, although it's valuable to myself to have figured this out.

Previously I was under the impression that there had to be a compatible license path from each of the lowest dependencies right up through to the piece of work using them whereby the license had to have same or stronger protections and otherwise be compatible at each step up the chain. So for instance:

```text
[Bin @ GPLv3]
    [Lib @ LGPLv3]
        [A @ Apache-2.0]
            [B @ MIT]
                [C @ MIT OR Apache-2.0]
```
...would be fine, but if the licenses of A and B were swapped, that would be incompatible since A could not compatibly make use of B. I believe now that this was completely wrong.

A few key helpful things I dug up were these:
 1. The diagram [here](https://blog.thehyve.nl/blog/open-source-software-licenses-3) under the heading 'license upgrade paths' is an excellent one in terms of clarity to assist in understanding compatibility, and what licences "subsume" what others I guess per the discussion at the next link. It shows and helps explain many of the compatible and incompatible relationships and is a lot clearer in some respects than that wikipedia image. Supposedly they had an actual lawyer there to guide them in writing their article, though who knows how correct that lawyer's knowledge/assessment was?
 2. [This authoritative discussion on license compatibility by the gnu](https://www.gnu.org/licenses/license-compatibility.en.html) which helps assert the validity of things like those diagrams. It points out some important details, most notably that when combining code, there is no elimination of weaker licenses where stronger ones incorporate their terms fully as I'd previously believed; all of the licenses simply apply to the final product, and a copy of each license must be kept with the respective code each covers. Inevitably one license will typically compatibly cover the terms of all others and thus will be the only one that needs to be read, but that's all that means.
 3. The [spdx spec](https://spdx.dev/spdx-specification-21-web-version/#h.jxpfx0ykyb60) allows AND based license combinations as well as OR, which covers such situations where multiple licenses apply. I expect this would be useful if say you had a crate with different licenses for different files.

This fresh understanding works well with the concept of individual crate licences applying only to the code within the crate, ignoring completely the licenses of its dependencies. This would apply to bin crates as well as libs; and the author of a bin (or lib compiled to a shared lib) just needs to check that the set of licences of itself and all collective dependencies just do not have any incompatibilities, such as an Apache-2.0 only crates mixed with a [L]GPLv1/2 crate.

Essentially this boils down to there not actually being any issue to fix with the `nalgebra` crates, so I'll close this now.

That said, I do have a concern about Apache-2.0 only licensing of crates. There are many existing programs and libraries out there that if they ever approach converting to Rust will be doing so via conversion rather than a replacement of their codebases no doubt (as is the case with a big one I am involved with), and will be thus sticking to their existing licensing. Many such projects have been sticking to [L]PLGv2 to avoid v3 I believe. With Apache-2.0 incompatible with [L]GPLv2, this presents a problem if they want/need to use Apache-2.0 only crates in such later conversion work. :/

**Comment by Andlon** [comment]
@jnqnfe: I don't think what we've done here constitutes a waste of time: `nalgebra` is growing increasingly popular and has already been integrated in many projects. It's important to know where the projects stands in terms of licensing, and I think this thread has helped with this.

I do agree that the license incompatibility caused by Apache 2.0 and (L)GPL v2 would be worth preventing, if possible. I'm not sure how to go about doing that, however.

Is it the case that `nalgebra` at the moment has dependencies that are Apache 2.0? I'm wondering if relicensing `nalgebra` even solves the issue - if some of its dependencies have incompatible licenses, then it's not a problem we could easily solve (barring switching out the dependency altogether).

**Comment by jnqnfe** [comment]
> Is it the case that `nalgebra` at the moment has dependencies that are Apache 2.0? I'm wondering if relicensing `nalgebra` even solves the issue - if some of its dependencies have incompatible licenses, then it's not a problem we could easily solve (barring switching out the dependency altogether).

Current Apache-2.0 only direct dependencies of `nalgebra` are `approx`, `simba` and `alga`. So those would need replacing or would need to be re-licensed themselves. Then all of the many dependencies all of the direct dependencies and so on would need checking. I won't bother to do that at this time.
