### ISSUE TITLE
num_traits dependency required for Zero,One, is_zero

### ISSUE THREAD

**Issue by WeiPhil** [dimforge/nalgebra#826]
Hello,
First of all, thank you for this amazing library, all the functionalities are amazing. 
I have noticed that I needed to add the num_traits crate in my dependencies to get access to some of the handy functions for my matrices. For example, `is_zero()`, or  [`Zero::zero()`](https://nalgebra.org/docs/user_guide/vectors_and_matrices) are not available out of the box. Is this expected? And if yes, what is the best way to avoid conflicting dependencies? Should I just use `num_traits = "*"` in my cargo dependencies?
Best,
Philippe

**Comment by sebcrozet** [comment]
Hi!

Instead of `Zero::zero()`, you can use the function `nalgebra::zero`. But to use `.is_zero()` you need to import `num_traits`. I guess we should re-export `num_traits` so that you could do `use nalgebra::num::Zero`.

Or you can look at the list of dependencies of `nalgebra`, the version of `num_traits` you need to import will be indicated (currently it's `0.2` and this dependency rarely has major version bumps).

**Comment by WeiPhil** [comment]
Thank you for your answer, re-exporting num traits would be quite nice indeed, along with num_traits approx is another library I had to "re-add" but that's not really an issue. Thanks for clarifying, I will close this :)
