### ISSUE TITLE
Flattening vector of matrices with the recent switch to const generics

### ISSUE THREAD

**Issue by WeiPhil** [dimforge/nalgebra#902]
Hello, before the recent switch to using const generics in the library I use to be able to flatten vector of matrices using something like
```let vertex_data = vector_matrix.into_iter().flat_map(|m| m.data.into_iter()).collect::<Vec<f32>>();```

However, this doesn't seem to work anymore. For example when I have a Vec<Vector3<f32>> and I want to flatten it into a Vec<f32>. Now I am getting :
_"the method 'flat_map' exists for struct 'Vec<Matrix<f32, Const<3_usize>,Const<1_usize>, ArrayStorage<f32, 3_usize,1_usize>>>', but its trait bounds where not satisfied_

How would this be done efficiently now?

**Comment by WeiPhil** [comment]
I just discovered that I can do
`let vertex_data = vector_matrix.iter().flat_map(|v| v).cloned().collect::<Vec<f32>>();`
instead and this seems to work. However, is this the best/efficient way of doing this currently?

**Comment by sebcrozet** [comment]
Hi! So `m.data.into_iter()` is no longer possible for statically-sized matrices because they use an array as their internal storage, and arrays don't implement `into_iter()` correctly currently (it returns a by-ref iterator instead of by-value). This will be fixed with the edition 2021 of Rust which will properly implement a by-value `into_iter()`.

In the  mean time, the solution you found looks good. For matrices with elements of type `f32`, this should not make any difference performance wise in release mode.

Regarding your `SVector::repeat` vs `OVector::repeat`, the problem is that with `OVector::repeat` the compiler isn't able to infer the correct version of `::repeat` it needs to call (because we have multiple `fn repeat` based on whether or not the vector has a dynamic number of elements). It could sound reasonable that the compiler would be able to infer the correct version from the fact that you expect a `OVector<f32, Const<N>>`, but it's not the case (I guess that the selection of the `::repeat` implementation is done before the inference of the speciallized type).

The `SVector::repeat` on the other hand works because the compiler knows immediately that it's dealing with a statically-sized vector, so the `::repeat` method it has to select must be the one for statically-sized vectors.

By the way, note that you can write `pub struct Wrapper<const N: usize>(SVector<f32, N>);` (it's equivalent to your `OVector` but without the need for `Const< >`.)

**Comment by WeiPhil** [comment]
Thank you so much for those details, that clarifies a lot!
